import Link from "next/link";
import { Building2, ArrowLeft, ScrollText } from "lucide-react";

const sections = [
  {
    n: "01",
    title: "Service description",
    body: (
      <>
        <p>
          Baltic Earnings Intelligence is a private-preview financial document
          workflow tool operated by DealSpacer. It enables users to upload
          earnings filings, extract structured data, and compare reported
          metrics across Baltic listed companies.
        </p>
      </>
    ),
  },
  {
    n: "02",
    title: "AI-generated content",
    body: (
      <>
        <p>
          Reports generated by this service are AI-assisted summaries produced
          from uploaded source filings. They may contain errors, omissions, or
          interpretive inaccuracies. The extracted figures and narratives are
          not guaranteed to be complete or correct.
        </p>
        <p className="mt-3">
          Users are solely responsible for verifying all figures and statements
          against the original source filings before relying on them.
        </p>
      </>
    ),
  },
  {
    n: "03",
    title: "Not financial advice",
    body: (
      <>
        <p>
          Nothing on this platform constitutes financial advice, investment
          recommendations, or an offer to buy or sell any securities.
        </p>
        <p className="mt-3">
          Baltic Earnings Intelligence is an informational tool only. Any
          decisions made on the basis of content generated by this service are
          made at the user&apos;s own risk and discretion.
        </p>
      </>
    ),
  },
  {
    n: "04",
    title: "Acceptable use",
    body: (
      <>
        <p>
          Users may not upload documents they do not have the right to process,
          attempt to reverse-engineer the service, or use generated output in
          ways that misrepresent its AI-assisted origin.
        </p>
        <p className="mt-3">
          Access to the service may be revoked at any time during private
          preview at our sole discretion.
        </p>
      </>
    ),
  },
  {
    n: "05",
    title: "Contact",
    body: (
      <>
        <p>
          For service questions, billing, or terms inquiries, contact us at{" "}
          <a
            href="mailto:hello@dealspacer.com"
            className="text-[#2b79db] transition hover:text-[#3d8de8]"
          >
            hello@dealspacer.com
          </a>
          .
        </p>
      </>
    ),
  },
];

export default function TermsPage() {
  return (
    <div className="relative min-h-screen bg-[#080b10] text-[#e8ecf2] font-[family-name:var(--font-body)]">
      <div className="landing-grain pointer-events-none fixed inset-0 z-[1]" aria-hidden />
      <div className="landing-aurora pointer-events-none fixed inset-0 z-0" aria-hidden />

      <div className="relative z-10 flex min-h-screen flex-col">
        {/* Header */}
        <header className="sticky top-0 z-40 border-b border-[#2b79db]/12 bg-[#080b10]/85 backdrop-blur-md">
          <div className="mx-auto flex w-full max-w-[1180px] items-center justify-between px-6 py-4 md:px-10">
            <Link
              href="/"
              className="flex items-center gap-2 font-[family-name:var(--font-mono)] text-[11px] uppercase tracking-[0.14em] text-[#8b9aad] transition hover:text-[#e8ecf2]"
            >
              <ArrowLeft className="size-3.5" />
              Back
            </Link>
            <span className="flex items-center gap-2 font-[family-name:var(--font-mono)] text-[11px] uppercase tracking-[0.14em] text-[#5a8f8f]">
              <ScrollText className="size-3.5" />
              Terms of Service
            </span>
          </div>
        </header>

        {/* Document */}
        <main className="mx-auto w-full max-w-[820px] flex-1 px-6 py-16 md:px-10 md:py-24">
          {/* Document meta strip */}
          <div className="flex flex-wrap items-center gap-x-6 gap-y-1 font-[family-name:var(--font-mono)] text-[10px] uppercase tracking-[0.2em] text-[#6b7d92]">
            <span>Baltic Earnings Intelligence</span>
            <span className="text-[#2a3544]">·</span>
            <span>Classification: Public</span>
            <span className="text-[#2a3544]">·</span>
            <span>Version 1.0</span>
          </div>

          {/* Title block */}
          <div className="relative mt-6 border-l-2 border-[#5a8f8f] pl-6">
            <h1 className="font-[family-name:var(--font-display)] text-[clamp(2rem,5vw,3.5rem)] font-medium leading-[1.05] tracking-[-0.02em] text-[#f4f6f9]">
              Terms of Service
            </h1>
            <p className="mt-3 max-w-lg text-base leading-relaxed text-[#8b9aad]">
              The conditions under which Baltic Earnings Intelligence is
              provided, including scope of the service, limitations, and
              acceptable use.
            </p>
          </div>

          {/* Divider */}
          <div className="mt-10 flex items-center gap-4">
            <div className="h-px flex-1 bg-gradient-to-r from-[#5a8f8f]/40 via-[#2a3544] to-transparent" />
            <span className="font-[family-name:var(--font-mono)] text-[10px] uppercase tracking-[0.18em] text-[#3d4d62]">
              Document
            </span>
          </div>

          {/* Sections */}
          <div className="mt-10 space-y-0">
            {sections.map((section, i) => (
              <div
                key={section.n}
                className="group relative grid grid-cols-[56px_1fr] gap-6 border-b border-[#1e2733] py-8 last:border-b-0"
              >
                {/* Vertical connector */}
                {i < sections.length - 1 && (
                  <div
                    className="pointer-events-none absolute bottom-0 left-[27px] top-8 w-px bg-gradient-to-b from-[#2a3544] to-transparent"
                    aria-hidden
                  />
                )}

                {/* Number */}
                <div className="relative z-10 pt-0.5">
                  <span className="font-[family-name:var(--font-mono)] text-[11px] tabular-nums text-[#5a8f8f]">
                    {section.n}
                  </span>
                </div>

                {/* Content */}
                <div>
                  <h2 className="font-[family-name:var(--font-display)] text-xl font-medium text-[#f4f6f9]">
                    {section.title}
                  </h2>
                  <div className="mt-3 text-[15px] leading-relaxed text-[#8b9aad]">
                    {section.body}
                  </div>
                </div>
              </div>
            ))}
          </div>

          {/* Disclaimer callout */}
          <div className="mt-12 flex items-start gap-3 border border-[#2a3544] bg-[#0c1018]/60 p-5">
            <span className="mt-0.5 block size-1.5 shrink-0 rounded-full bg-[#5a8f8f]" />
            <p className="font-[family-name:var(--font-mono)] text-[11px] leading-relaxed text-[#6b7d92]">
              These terms apply to the Baltic Earnings Intelligence service
              during private preview. By using the service, you agree to these
              conditions. We reserve the right to update these terms as the
              product evolves.
            </p>
          </div>
        </main>

        {/* Footer */}
        <footer className="border-t border-[#1e2733] py-10">
          <div className="mx-auto flex w-full max-w-[1180px] flex-wrap items-center justify-between gap-4 px-6 text-sm text-[#6b7d92] md:px-10">
            <span className="flex items-center gap-2 font-[family-name:var(--font-mono)] text-[11px] uppercase tracking-[0.1em]">
              <Building2 className="size-3.5 text-[#2b79db]" />
              © Baltic Earnings Intelligence
            </span>
            <nav className="flex gap-6 font-[family-name:var(--font-mono)] text-[11px] uppercase tracking-[0.1em]">
              <Link href="/privacy" className="transition hover:text-[#e8ecf2]">
                Privacy
              </Link>
              <Link href="/terms" className="text-[#e8ecf2]">
                Terms
              </Link>
              <Link href="/access" className="transition hover:text-[#e8ecf2]">
                Access
              </Link>
            </nav>
          </div>
        </footer>
      </div>
    </div>
  );
}
