/**
 * Baltic listed companies — Nasdaq Baltic share lists (Main, Secondary, First North Baltic, FN foreign).
 * Synced from https://nasdaqbaltic.com/statistics/en/shares (2026-05-15).
 * Regenerate: node packages/shared/scripts/sync-nasdaq-baltic-seed.mjs
 * Run idempotently — uses ON CONFLICT (slug) DO UPDATE.
 */
import type { SeedCompany } from "./index";

export const BALTIC_COMPANIES: SeedCompany[] = [
  { name: "Airobot Technologies", ticker: "AIR", exchange: "Nasdaq Tallinn", slug: "airobot-technologies", country: "EE", sector: "Industrials" },
  { name: "Arco Vara", ticker: "ARC1T", exchange: "Nasdaq Tallinn", slug: "arco-vara", country: "EE", sector: "Real Estate" },
  { name: "Bercman Technologies", ticker: "BERCM", exchange: "Nasdaq Tallinn", slug: "bercman-technologies", country: "EE", sector: "Industrials" },
  { name: "Coop Pank", ticker: "CPA1T", exchange: "Nasdaq Tallinn", slug: "coop-pank", country: "EE", sector: "Financials" },
  { name: "EfTEN Real Estate Fund", ticker: "EFT1T", exchange: "Nasdaq Tallinn", slug: "eften-real-estate-fund", country: "EE", sector: "Financials" },
  { name: "Ekspress Grupp", ticker: "EEG1T", exchange: "Nasdaq Tallinn", slug: "ekspress-grupp", country: "EE", sector: "Consumer Discretionary" },
  { name: "Estonian Japan Trading Company", ticker: "EJTC", exchange: "Nasdaq Tallinn", slug: "estonian-japan-trading-company", country: "EE", sector: "Financials" },
  { name: "Grab2Go", ticker: "GRB2G", exchange: "Nasdaq Tallinn", slug: "grab2go", country: "EE", sector: "Industrials" },
  { name: "AS Harju Elekter", ticker: "HAE1T", exchange: "Nasdaq Tallinn", slug: "harju-elekter", country: "EE", sector: "Industrials" },
  { name: "Hepsor", ticker: "HPR1T", exchange: "Nasdaq Tallinn", slug: "hepsor", country: "EE", sector: "Real Estate" },
  { name: "Infortar", ticker: "INF1T", exchange: "Nasdaq Tallinn", slug: "infortar", country: "EE", sector: "Financials" },
  { name: "J. Molner", ticker: "MOLNR", exchange: "Nasdaq Tallinn", slug: "j-molner", country: "EE", sector: "Health Care" },
  { name: "LHV Group", ticker: "LHV1T", exchange: "Nasdaq Tallinn", slug: "lhv-group", country: "EE", sector: "Financials" },
  { name: "Linda Nektar", ticker: "LINDA", exchange: "Nasdaq Tallinn", slug: "linda-nektar", country: "EE", sector: "Consumer Staples" },
  { name: "Liven", ticker: "LVN1T", exchange: "Nasdaq Tallinn", slug: "liven", country: "EE", sector: "Real Estate" },
  { name: "Merko Ehitus", ticker: "MRK1T", exchange: "Nasdaq Tallinn", slug: "merko-ehitus", country: "EE", sector: "Industrials" },
  { name: "Modera", ticker: "MODE", exchange: "Nasdaq Tallinn", slug: "modera", country: "EE", sector: "Technology" },
  { name: "Nordecon", ticker: "NCN1T", exchange: "Nasdaq Tallinn", slug: "nordecon", country: "EE", sector: "Industrials" },
  { name: "Nordic Fibreboard", ticker: "SKN1T", exchange: "Nasdaq Tallinn", slug: "nordic-fibreboard", country: "EE", sector: "Consumer Discretionary" },
  { name: "PRFoods", ticker: "PRF1T", exchange: "Nasdaq Tallinn", slug: "prfoods", country: "EE", sector: "Consumer Staples" },
  { name: "Primostar Group", ticker: "PRIMO", exchange: "Nasdaq Tallinn", slug: "primostar-group", country: "EE", sector: "Consumer Discretionary" },
  { name: "Pro Kapital Grupp", ticker: "PKG1T", exchange: "Nasdaq Tallinn", slug: "pro-kapital", country: "EE", sector: "Real Estate" },
  { name: "Punktid Technologies", ticker: "PNKTD", exchange: "Nasdaq Tallinn", slug: "punktid-technologies", country: "EE", sector: "Technology" },
  { name: "Robus Group", ticker: "ROBUS", exchange: "Nasdaq Tallinn", slug: "robus-group", country: "EE", sector: "Consumer Discretionary" },
  { name: "Saunum Group", ticker: "SAUNA", exchange: "Nasdaq Tallinn", slug: "saunum-group", country: "EE", sector: "Consumer Discretionary" },
  { name: "Silvano Fashion Group", ticker: "SFG1T", exchange: "Nasdaq Tallinn", slug: "silvano-fashion", country: "EE", sector: "Consumer Discretionary" },
  { name: "Tallink Grupp", ticker: "TAL1T", exchange: "Nasdaq Tallinn", slug: "tallink-grupp", country: "EE", sector: "Consumer Discretionary" },
  { name: "Tallinna Sadam", ticker: "TSM1T", exchange: "Nasdaq Tallinn", slug: "tallinna-sadam", country: "EE", sector: "Industrials" },
  { name: "Tallinna Vesi", ticker: "TVE1T", exchange: "Nasdaq Tallinn", slug: "tallinna-vesi", country: "EE", sector: "Utilities" },
  { name: "TextMagic", ticker: "MAGIC", exchange: "Nasdaq Tallinn", slug: "textmagic", country: "EE", sector: "Telecommunications" },
  { name: "TKM Grupp", ticker: "TKM1T", exchange: "Nasdaq Tallinn", slug: "tallinna-kaubamaja", country: "EE", sector: "Consumer Discretionary" },
  { name: "Trigon Property Development", ticker: "TPD1T", exchange: "Nasdaq Tallinn", slug: "trigon-property-development", country: "EE", sector: "Real Estate" },
  { name: "Agrova Baltics", ticker: "EGG", exchange: "Nasdaq Riga", slug: "agrova-baltics", country: "LV", sector: "Consumer Staples" },
  { name: "Amber Latvijas balzams", ticker: "BAL1R", exchange: "Nasdaq Riga", slug: "amber-latvijas-balzams", country: "LV", sector: "Consumer Staples" },
  { name: "DelfinGroup", ticker: "DGR1R", exchange: "Nasdaq Riga", slug: "delfingroup", country: "LV", sector: "Financials" },
  { name: "Eleving Group", ticker: "ELEVR", exchange: "Nasdaq Riga", slug: "eleving-group", country: "LV", sector: "Financials" },
  { name: "Frigate", ticker: "FRGTE", exchange: "Nasdaq Riga", slug: "frigate", country: "LV", sector: "Financials" },
  { name: "INDEXO", ticker: "IDX1R", exchange: "Nasdaq Riga", slug: "indexo", country: "LV", sector: "Financials" },
  { name: "Kalve Coffee", ticker: "KALVE", exchange: "Nasdaq Riga", slug: "kalve-coffee", country: "LV", sector: "Consumer Staples" },
  { name: "MADARA Cosmetics", ticker: "MDARA", exchange: "Nasdaq Riga", slug: "madara-cosmetics", country: "LV", sector: "Consumer Discretionary" },
  { name: "Rīgas kuģu būvētava", ticker: "RKB1R", exchange: "Nasdaq Riga", slug: "rigas-kugu-buvetava", country: "LV", sector: "Industrials" },
  { name: "SAF Tehnika", ticker: "SAF1R", exchange: "Nasdaq Riga", slug: "saf-tehnika", country: "LV", sector: "Telecommunications" },
  { name: "Siguldas ciltslietu un mākslīgās apsēklošanas stacija", ticker: "SCM1R", exchange: "Nasdaq Riga", slug: "siguldas-cmas", country: "LV", sector: "Consumer Staples" },
  { name: "VIRŠI-A", ticker: "VIRSI", exchange: "Nasdaq Riga", slug: "virsi-a", country: "LV", sector: "Consumer Discretionary" },
  { name: "Akola Group", ticker: "AKO1L", exchange: "Nasdaq Vilnius", slug: "akola-group", country: "LT", sector: "Consumer Staples" },
  { name: "Amber Grid", ticker: "AMG1L", exchange: "Nasdaq Vilnius", slug: "amber-grid", country: "LT", sector: "Energy" },
  { name: "Apranga", ticker: "APG1L", exchange: "Nasdaq Vilnius", slug: "apranga", country: "LT", sector: "Consumer Discretionary" },
  { name: "Artea Bankas", ticker: "ROE1L", exchange: "Nasdaq Vilnius", slug: "artea-bankas", country: "LT", sector: "Financials" },
  { name: "AUGA group", ticker: "AUG1L", exchange: "Nasdaq Vilnius", slug: "auga-group", country: "LT", sector: "Consumer Staples" },
  { name: "City Service", ticker: "CTS1L", exchange: "Nasdaq Vilnius", slug: "city-service", country: "LT", sector: "Industrials" },
  { name: "East West Agro", ticker: "EWA1L", exchange: "Nasdaq Vilnius", slug: "east-west-agro", country: "LT", sector: "Industrials" },
  { name: "AB Grigeo", ticker: "GRG1L", exchange: "Nasdaq Vilnius", slug: "grigeo", country: "LT", sector: "Basic Materials" },
  { name: "Ignitis grupė", ticker: "IGN1L", exchange: "Nasdaq Vilnius", slug: "ignitis-grupe", country: "LT", sector: "Utilities" },
  { name: "Invalda INVL", ticker: "IVL1L", exchange: "Nasdaq Vilnius", slug: "invalda-invl", country: "LT", sector: "Financials" },
  { name: "INVL Baltic Farmland", ticker: "INL1L", exchange: "Nasdaq Vilnius", slug: "invl-baltic-farmland", country: "LT", sector: "Real Estate" },
  { name: "INVL Baltic Real Estate", ticker: "INR1L", exchange: "Nasdaq Vilnius", slug: "invl-baltic-real-estate", country: "LT", sector: "Real Estate" },
  { name: "INVL Technology", ticker: "INC1L", exchange: "Nasdaq Vilnius", slug: "invl-technology", country: "LT", sector: "Financials" },
  { name: "K2 LT", ticker: "K2LT", exchange: "Nasdaq Vilnius", slug: "k2-lt", country: "LT", sector: "Consumer Discretionary" },
  { name: "Kauno energija", ticker: "KNR1L", exchange: "Nasdaq Vilnius", slug: "kauno-energija", country: "LT", sector: "Utilities" },
  { name: "KN Energies", ticker: "KNE1L", exchange: "Nasdaq Vilnius", slug: "kn-energies", country: "LT", sector: "Industrials" },
  { name: "LITGRID", ticker: "LGD1L", exchange: "Nasdaq Vilnius", slug: "litgrid", country: "LT", sector: "Utilities" },
  { name: "NEO Finance", ticker: "NEOFI", exchange: "Nasdaq Vilnius", slug: "neo-finance", country: "LT", sector: "Financials" },
  { name: "Novaturas", ticker: "NTU1L", exchange: "Nasdaq Vilnius", slug: "novaturas", country: "LT", sector: "Consumer Discretionary" },
  { name: "Pieno žvaigždės", ticker: "PZV1L", exchange: "Nasdaq Vilnius", slug: "pieno-zvaigzdes", country: "LT", sector: "Consumer Staples" },
  { name: "Rokiškio sūris", ticker: "RSU1L", exchange: "Nasdaq Vilnius", slug: "rokiskio-suris", country: "LT", sector: "Consumer Staples" },
  { name: "Telia Lietuva", ticker: "TEL1L", exchange: "Nasdaq Vilnius", slug: "telia-lietuva", country: "LT", sector: "Telecommunications" },
  { name: "Utenos trikotažas", ticker: "UTR1L", exchange: "Nasdaq Vilnius", slug: "utenos-trikotazas", country: "LT", sector: "Consumer Discretionary" },
  { name: "Vilkyškių pieninė", ticker: "VLP1L", exchange: "Nasdaq Vilnius", slug: "vilkyškiu-pienine", country: "LT", sector: "Consumer Staples" },
  { name: "Vilniaus baldai", ticker: "VBL1L", exchange: "Nasdaq Vilnius", slug: "vilniaus-baldai", country: "LT", sector: "Consumer Discretionary" },
  { name: "Žemaitijos pienas", ticker: "ZMP1L", exchange: "Nasdaq Vilnius", slug: "zemaitijos-pienas", country: "LT", sector: "Consumer Staples" },
];
